"""initial schema

Revision ID: 2ea6078a8ca4
Revises: 
Create Date: 2026-07-04 21:31:32.521222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea6078a8ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('equity_curve_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_pairs', sa.JSON(), nullable=False),
    sa.Column('cycle_ms', sa.Integer(), nullable=False),
    sa.Column('flags_seen', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('key', name='uq_control_flag_key')
    )
    op.create_table('equity_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('open_pnl', sa.Float(), nullable=False),
    sa.Column('margin_used', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_positions_override', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument'),
    sa.UniqueConstraint('instrument', name='uq_instrument_control_instrument')
    )
    op.create_table('regime_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('bars_in_regime', sa.Integer(), nullable=False),
    sa.Column('candles_fresh', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('vetoes', sa.JSON(), nullable=False),
    sa.Column('indicator_snapshot', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('oanda_order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('spread_at_entry', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('oanda_trade_id', sa.String(length=64), nullable=False),
    sa.Column('open_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_px', sa.Float(), nullable=False),
    sa.Column('exit_px', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_r', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oanda_trade_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('order')
    op.drop_table('signal_log')
    op.drop_table('regime_snapshot')
    op.drop_table('instrument_control')
    op.drop_table('equity_snapshot')
    op.drop_table('control_flag')
    op.drop_table('bot_heartbeat')
    op.drop_table('backtest_run')
    # ### end Alembic commands ###
